# language: node_js
# node_js:
#   - "9.11.2"

language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greeted_users

node_js:  
  - "9.11.2"

before_script:
  - psql -c 'create database  greeted_users_tests;' -U postgres
  - psql -U postgres -d greeted_users_tests -a -f database-table.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2